# Settings for the [build] key are global and are applied to
# all deploy contexts unless overridden by a context-specific setting.
[build]
  # Default build command.
  functions = "dist"
  publish = "dist"
  command = "npm run build"
  environment = { NODE_VERSION = "22.8.0" }

# Redirects for role-based access control don’t use the 'to' property.
# The following redirect is intended for use with most SPAs
# that handle routing internally.
[[redirects]]
  from = "/"
  to = "/index.html"
  status = 301

